[project]
name = "genir"
version = "0.1.0"
description = "A tool for generating intermediate representations (IR) for machine learning models on TPUs."
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["jax>=0.4.0"]
