name: ci
on:
  push:
    branches:
      - master
    tags:
      - "*"
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: ${{ !contains(github.ref, 'master')}}

jobs:
  platforms:
    strategy:
      matrix:
        platforms:
          - target: cuda
            bazel_opts: "--@zml//runtimes:cuda=true --@zml//runtimes:cpu=false"
            enable_cache: false
            user: actions
            runs-on: ["self-hosted", "platform=cuda"]
          - target: rocm
            bazel_opts: "--@zml//runtimes:rocm=true --@zml//runtimes:cpu=false"
            enable_cache: false
            user: actions
            runs-on: ["self-hosted", "platform=rocm"]
          - target: cpu
            bazel_opts: "--@zml//runtimes:cpu=true"
            enable_cache: true
            user: runner
            runs-on:
              [
                "runs-on",
                "runner=4cpu-linux-x64",
                "image=ubuntu24-amd64",
                "run-id=${{ github.run_id }}",
                "extras=s3-cache",
              ]
    runs-on: ${{ matrix.platforms.runs-on }}
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4
      - uses: runs-on/snapshot@v1
        if: ${{ matrix.platforms.enable_cache }}
        with:
          path: /home/runner/.cache/bazel-disk
          volume_size: 350
      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: 1.26.0
          bazelisk-cache: false
          # todo: use `--config=debug` instead of `-c opt` when static archive bug is fixed
          bazelrc: |
            common -c opt
            common --verbose_failures
            common --keep_going
            common --test_output=streamed
            common --color=yes
            common --show_timestamps
            common --disk_cache=/home/${{ matrix.platforms.user }}/.cache/bazel-disk
            common --strip=always

      - name: ZML / bazel build //...
        run: bazel build ${{ matrix.platforms.bazel_opts }} //...

      - name: ZML / bazel test //...
        run: bazel test ${{ matrix.platforms.bazel_opts }} //...
  ci:
    runs-on:
      [
        "runs-on",
        "runner=4cpu-linux-x64",
        "image=ubuntu24-amd64",
        "run-id=${{ github.run_id }}",
        "extras=s3-cache",
      ]
    steps:
      - uses: runs-on/action@v1
      - name: Checkout
        uses: actions/checkout@v4

      - uses: runs-on/snapshot@v1
        with:
          path: /home/runner/.cache/bazel-disk
          volume_size: 350

      - name: TMP fix for the mount user
        run: sudo chown -R runner:runner /home/runner/.cache/

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: 0.15.1
          mirror: https://mirror.zml.ai/zig

      - name: Zig Format
        run: zig fmt --check  $(git ls-files --exclude-standard -- ':!third_party/*' '*.zig' | xargs)

      - name: No autofix in Zig code
        run: bash -c "! git grep -l '// autofix' -- '*.zig'"

      - uses: bazel-contrib/setup-bazel@0.15.0
        with:
          bazelisk-version: 1.26.0
          bazelisk-cache: false
          # todo: use `--config=debug` instead of `-c opt` when static archive bug is fixed
          bazelrc: |
            common -c opt
            common --verbose_failures
            common --keep_going
            common --test_output=streamed
            common --color=yes
            common --show_timestamps
            common --disk_cache=/home/runner/.cache/bazel-disk
            common --strip=always

      - name: ZML / bazel mod explain
        run: bazel mod explain

      - name: ZML / bazel mod graph
        run: bazel mod graph

      - name: ZML / bazel query //...
        run: bazel query //...
